### ISSUE TITLE
[ISSUE] Shulker box invisible

### ISSUE THREAD

**Issue by futamiy** [NeoNyaa/No-Block-Break-Particles#1]
Problem:
![image](https://github.com/user-attachments/assets/6391047d-d980-45cc-a8b2-96968d964070)
Expected:
![image](https://github.com/user-attachments/assets/1ea14128-3aa7-452b-9f64-3bf3d86e061b)

Also using mod immediately fast

**Comment by NeoNyaa** [comment]
If you are using the mod **"Enhanced Block Entities"**, it's known to cause issues with this pack for some reason.

Check the first entry in known bugs.

If, for whatever reason, this doesn't fix your issue, please send me a screenshot/list of the contents of your mods folder, so I can do my own testing.

**Comment by futamiy** [comment]
Mods:
- alternate-current 1.9.0
	- appleskin 3.0.5+mc1.21
	- architectury 13.0.6
	- autoclicky 1.2.1
	- autofish 1.3.0-fabric-mc1.21
	- autoswitch 9.1.1
	   \-- autoswitch-api 3.0.0
	- axiom 4.1.0
	   |-- com_moulberry_axiomclientapi_axiomclientapi_ 1.0.0
	   \-- com_moulberry_mixinconstraints 1.0.1
	- badoptimizations 2.1.4
	- badpackets 0.8.1
	- betterpingdisplay 1.1.1
	- bobby 5.2.4+mc1.21
	   |-- com_typesafe_config 1.4.2
	   |-- fabric-api-base 0.4.42+6573ed8c6a
	   |-- fabric-command-api-v2 2.2.28+6ced4dd96a
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- brb 1.10.0-rc5+1.21
	- bridgingmod 2.4.0+1.21
	- c2me 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-base 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-client-uncapvd 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-fixes-chunkio-threading-issues 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-fixes-general-threading-issues 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-fixes-worldgen-threading-issues 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-notickvd 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-allocs 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-chunk-access 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-chunkio 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-math 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-scheduling 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-worldgen-general 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-opts-worldgen-vanilla 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-rewrites-chunk-serializer 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-rewrites-chunk-system 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-rewrites-chunkio 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-server-utils 0.3.0+alpha.0.206+1.21.1
	   |-- c2me-threading-lighting 0.3.0+alpha.0.206+1.21.1
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- io_reactivex_rxjava3_rxjava 3.1.8
	   |-- mixinsquared 0.2.0-beta.6
	   |-- net_objecthunter_exp4j 0.4.8
	   |-- org_jctools_jctools-core 4.0.5
	   \-- org_reactivestreams_reactive-streams 1.0.4
	- capes 1.5.4+1.21
	- chesttracker 2.5.3+1.21.1
	   \-- searchables 1.0.1
	- chunky 1.4.16
	- clickthrough 3.0+1.21
	- cloth-config 15.0.130
	   \-- cloth-basic-math 0.6.1
	- clumps 19.0.0.1
	- concentration 1.1.8
	- connectivity 1.21-5.7
	- continuity 3.0.0-beta.5+1.21
	- cupboard 1.21-2.7
	- debugify 1.21.1+1.0
	- dynamic_fps 3.6.3
	   \-- net_lostluma_battery 1.1.0
	- enhancedblockentities 0.10.1+1.21
	- entityculling 1.7.0
	- essentialgui 1.10.1
	- f3teverywhere 1.0.1
	- fabric-api 0.104.0+1.21.1
	   |-- fabric-api-lookup-api-v1 1.6.68+b559734419
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bc19
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.16+b559734419
	   |-- fabric-convention-tags-v1 2.0.22+7f945d5b19
	   |-- fabric-convention-tags-v2 2.7.0+4053855719
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.1.28+1daea21519
	   |-- fabric-data-generation-api-v1 20.2.19+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.0.0+afdfc92119
	   |-- fabric-item-group-api-v1 4.1.5+3fc0e55219
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df36019
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.2.2+60c3209b19
	   |-- fabric-object-builder-api-v1 15.2.0+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.12+6508971219
	   |-- fabric-registry-sync-v0 5.1.2+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.0+5659912919
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.86+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.2.0+d38f898f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- fastchest 1.5+1.20.2
	- fastipping 1.0.4
	- fastquit 3.0.0+1.20.6
	- fasttrading 0.1.5+1.21
	- ferritecore 7.0.0
	- fpsreducer 1.21-2.9
	- freecam 1.3.0+mc1.21
	- globalpacks 21.0.0
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- immediatelyfast 1.2.21+1.21.1
	   \-- net_lenni0451_reflect 1.3.4
	- inventory_tabs 1.4.0+1.21
	   \-- folk_sisby_kaleido-config 0.3.1+1.3.2
	- inventoryprofilesnext 2.0.4
	- java 21
	- keybindfixplus 2.0.0
	- kiwi 15.1.1+fabric
	- krypton 0.2.8
	   \-- com_velocitypowered_velocity-native 3.3.0-SNAPSHOT
	- lazy-language-loader 0.3.7
	- libipn 6.0.2
	- lighty 3.0.0-beta.4
	- litematica 0.19.50
	- litematica_printer 7.2.1
	- lithium 0.13.0
	- malilib 0.21.0
	   \-- fabric-api-base 0.4.42+6573ed8c6a
	- minecraft 1.21.1
	- minieffects 9.0.1+fabric
	- minihud 0.32.50
	- modelfix 1.21-1.6
	- modernfix 5.19.3+mc1.21.1
	- modmenu 11.0.2
	- moreculling 0.27.1
	   \-- com_github_fallen-breath_conditional-mixin v0.6.2
	- mousetweaks 2.26
	- mr_datapack_reloadhelper 1.1.1
	- no-resource-pack-warnings 1.3.0
	- nochatreports 1.21-v2.8.0
	- noisium 2.3.0+mc1.21-1.21.1
	- obsidianui 0.2.7+mc1.21
	- optigui 2.3.0-beta.2+1.21
	   |-- org_apache_commons_commons-text 1.12.0
	   \-- org_ini4j_ini4j 0.5.4
	- optionsprofiles 1.3.1
	- phases-discord-rich-presence 1.4.1-1.21
	   |-- club_minnced_discord-rpc-release v3.4.0
	   |-- com_github_minndevelopment_java-discord-rpc v2.0.2
	   \-- midnightlib 1.5.6
	- reeses-sodium-options 1.8.0-beta.2+mc1.21.1
	- reset-keys-confirmation-screen 1.3.0
	- roughlyenoughitems 16.0.754
	   \-- error_notifier 1.0.9
	- ryoamiclights 0.2.11+mc1.21.1
	- screenshotclipboard 1.0.10
	- servercore 1.5.5+1.21.1
	   |-- fabric-permissions-api-v0 0.3.1
	   |-- org_yaml_snakeyaml 2.2
	   |-- placeholder-api 2.4.1+1.21
	   |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
	   \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
	- shulkerboxtooltip 5.1.1+1.21.1
	- skin_overrides 2.1.1+1.21
	- skinlayers3d 1.6.7
	- smoke_suppression 1.1.1
	- smoothchunk 1.21-3.6
	- sodium 0.6.0-beta.1+mc1.21
	- sodium-extra 0.6.0-beta.1+mc1.21.1
	   \-- com_lodborg_interval-tree 1.0.0
	- sodiumleafculling 1.0.0
	- spark 1.10.97
	   \-- fabric-permissions-api-v0 0.3.1
	- sspb 4.0.0-beta.1
	- threadtweak 0.1.5+mc1.21.1
	- tweakeroo 0.21.50
	- visuality 0.7.7+1.21
	- vmp 0.2.0+beta.7.167+1.21.1
	   \-- com_ibm_async_asyncutil 0.1.0
	- whereisit 2.6.2+1.21.1
	   \-- jackfredlib 0.10.2+1.21.1
	        |-- jackfredlib-base 1.4.1+1.21.1
	        |-- jackfredlib-colour 1.1.0+1.21.1
	        |-- jackfredlib-extracommandsourcedata 1.1.1+1.21.1
	        |-- jackfredlib-gps 1.0.7+1.21.1
	        |-- jackfredlib-lying 0.5.5+1.21.1
	        \-- jackfredlib-toasts 1.1.1+1.21.1
	- worldedit 7.3.6+6892-3d660b8
	- wthit 12.4.2
	- xaerominimap 24.4.0
	- xaeroworldmap 1.39.0
	- yet_another_config_lib_v3 3.5.0+1.21-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zume 1.1.2

**Comment by NeoNyaa** [comment]
I noticed that you have `enhancedblockentities 0.10.1+1.21`. This is known to cause issues with this pack and any other pack which messes around with the blocks model files, disable the Shulker box option in its config if you haven't done so already.

**Comment by NeoNyaa** [comment]
@futamiy Did disabling the Shulker box optimization option from the `enhancedblockentities 0.10.1+1.21` config menu fix your issue?

If no response is supplied, I will close this issue as `Stale`
